framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
        transports:
            doctrine:
                dsn: "%env(MESSENGER_DOCTRINE_TRANSPORT_DSN)%"
                serializer: 'messenger.transport.symfony_serializer'
            add_followers:
                dsn: "%env(MESSENGER_AMQP_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: 'old_sound_rabbit_mq.add_followers'
                        type: direct
                serializer: 'messenger.transport.symfony_serializer'
            send_notification:
                dsn: "%env(MESSENGER_AMQP_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: 'old_sound_rabbit_mq.send_notification'
                        type: topic
                serializer: 'messenger.transport.symfony_serializer'
            create_user:
                dsn: "%env(MESSENGER_AMQP_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: 'old_sound_rabbit_mq.create_user'
                        type: direct
            sync: 'sync://'

        routing:
            App\DTO\AddFollowersDTO: add_followers
            FeedBundle\DTO\SendNotificationDTO: doctrine
            App\DTO\SendNotificationAsyncDTO: send_notification
            App\Domain\Command\CreateUser\CreateUserCommand: create_user

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
