monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - elasticsearch

when@dev:
    monolog:
        handlers:
            elasticsearch:
                type: service
                id: Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler
                channels: elasticsearch
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

    services:
        Psr\Log\NullLogger:
            class: Psr\Log\NullLogger

        http_client_without_logs:
            class: Symfony\Component\HttpClient\CurlHttpClient
            calls:
                - [setLogger, ['@Psr\Log\NullLogger']]

        Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler:
            arguments:
                - 'http://elasticsearch:9200'
                - 'monolog'
                - '@http_client_without_logs'

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
