nelmio_api_doc:
    documentation:
        info:
            title: Twitter API
            description: Otus!
            version: 1.2.3
    areas: # to filter documented areas
        feed:
            path_patterns:
                - ^/api/v1/get-feed
        default:
            path_patterns:
                - ^/api(?!/doc(.json)?$)
