old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        add_followers:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.add_followers', type: direct}
        publish_tweet:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.publish_tweet', type: direct}
        send_notification:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.send_notification', type: topic}

    consumers:
        add_followers:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.add_followers', type: direct}
            queue_options: {name: 'old_sound_rabbit_mq.consumer.add_followers'}
            callback: App\Consumer\AddFollowers\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: {prefetch_size: 0, prefetch_count: 30, global: false}
        publish_tweet:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.publish_tweet', type: direct}
            queue_options: {name: 'old_sound_rabbit_mq.consumer.publish_tweet'}
            callback: App\Consumer\PublishTweet\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: {prefetch_size: 0, prefetch_count: 1, global: false}
        send_notification.email:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.send_notification', type: topic}
            queue_options:
                name: 'old_sound_rabbit_mq.consumer.send_notification.email'
                routing_keys: [!php/const App\Entity\User::EMAIL_NOTIFICATION]
            callback: App\Consumer\SendEmailNotification\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: {prefetch_size: 0, prefetch_count: 1, global: false}
        send_notification.sms:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.send_notification', type: topic}
            queue_options:
                name: 'old_sound_rabbit_mq.consumer.send_notification.sms'
                routing_keys: [!php/const App\Entity\User::SMS_NOTIFICATION]
            callback: App\Consumer\SendSmsNotification\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: {prefetch_size: 0, prefetch_count: 1, global: false}
