security:
    enable_authenticator_manager: true
    providers:
        users_in_memory:
            memory:
                users:
                    admin:
                        password: 'my_pass'
                        roles: 'ROLE_ADMIN'
                    user:
                        password: 'other_pass'
                        roles: 'ROLE_USER'

    password_hashers:
        App\Entity\User: auto
        Symfony\Component\Security\Core\User\InMemoryUser: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic:
                realm: Secured Area
            lazy: true
            provider: users_in_memory

    access_control:
        - { path: ^/api/v4/users, roles: ROLE_ADMIN }