openapi: 3.0.0
info:
  title: 'Twitter API'
  description: Otus!
  version: 1.2.3
paths:
  '/api/v2/user/by-login/{userLogin}':
    get:
      operationId: get_app_api_v2_user_getuserbylogin
      parameters:
        -
          name: userLogin
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: ''
  /api/v1/add-followers:
    post:
      operationId: post_app_api_addfollowers_v1_addfollowers
      requestBody:
        content:
          application/json:
            schema:
              required:
                - userId
                - followersLogin
                - count
                - async
              properties:
                userId:
                  type: string
                  default: null
                  pattern: \d+
                followersLogin:
                  type: string
                  default: null
                count:
                  type: string
                  default: null
                  pattern: \d+
                async:
                  type: string
                  default: null
                  pattern: 0|1
              type: object
      responses:
        default:
          description: ''
  /api/v4/users:
    post:
      operationId: post_app_api_createuser_v4_createuseraction__invoke
      requestBody:
        content:
          application/json:
            schema:
              required:
                - login
                - password
                - roles
                - age
                - isActive
              properties:
                login:
                  type: string
                  default: null
                password:
                  type: string
                  default: null
                roles:
                  type: string
                  default: null
                age:
                  type: string
                  default: null
                  pattern: \d+
                isActive:
                  type: string
                  default: null
                  pattern: true|false
              type: object
      responses:
        default:
          description: ''
  /api/v5/users:
    post:
      operationId: post_app_api_createuser_v5_createuseraction_saveuser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDTO'
      responses:
        default:
          description: ''
  /api/v1/get-feed:
    get:
      tags:
        - Лента
      operationId: get_app_api_getfeed_v1_getfeed
      parameters:
        -
          name: userId
          in: query
          description: 'ID пользователя'
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
            pattern: \d+
          example: '135'
        -
          name: count
          in: query
          description: 'Количество на странице'
          required: false
          allowEmptyValue: true
          schema:
            type: string
            default: null
            pattern: \d+
          example: '1'
      responses:
        default:
          description: ''
  /api/v1/tweet:
    get:
      operationId: get_app_api_gettweets_v1_gettweets
      responses:
        default:
          description: ''
    post:
      operationId: post_app_api_savetweet_v1_savetweet
      requestBody:
        content:
          application/json:
            schema:
              required:
                - authorId
                - text
              properties:
                authorId:
                  type: string
                  default: null
                  pattern: \d+
                text:
                  type: string
                  default: null
                async:
                  type: string
                  default: null
                  pattern: 0|1
              type: object
      responses:
        default:
          description: ''
  '/api/v4/users.{format}':
    get:
      operationId: get_app_api_getusers_v4_getusersaction__invoke
      parameters:
        -
          name: perPage
          in: query
          required: false
          schema:
            type: integer
            nullable: true
        -
          name: page
          in: query
          required: false
          schema:
            type: integer
            nullable: true
        -
          name: format
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: ''
  /api/v1/get-users-by-query:
    get:
      operationId: get_app_api_getusersbyquery_v1_getusersbyquery
      parameters:
        -
          name: query
          in: query
          description: ''
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
        -
          name: perPage
          in: query
          description: ''
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
            pattern: \d+
        -
          name: page
          in: query
          description: ''
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
            pattern: \d+
      responses:
        default:
          description: ''
  /api/v1/get-users-by-query-with-aggregation:
    get:
      operationId: get_app_api_getusersbyquerywithaggregation_v1_getusersbyquerywithaggregation
      parameters:
        -
          name: query
          in: query
          description: ''
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
        -
          name: field
          in: query
          description: ''
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
      responses:
        default:
          description: ''
  /api/v1/get-users-with-aggregation:
    get:
      operationId: get_app_api_getuserswithaggregation_v1_getuserswithaggregation
      parameters:
        -
          name: field
          in: query
          description: ''
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
      responses:
        default:
          description: ''
  /api/v1/token:
    post:
      operationId: post_app_api_v1_token_gettoken
      responses:
        default:
          description: ''
  /api/v1/upload:
    post:
      operationId: post_app_api_v1_upload_uploadfile
      responses:
        default:
          description: ''
  /api/v1/user:
    get:
      operationId: get_app_api_v1_user_getusers
      responses:
        default:
          description: ''
    post:
      operationId: post_app_api_v1_user_saveuser
      responses:
        default:
          description: ''
    delete:
      operationId: delete_app_api_v1_user_deleteuser
      responses:
        default:
          description: ''
    patch:
      operationId: patch_app_api_v1_user_updateuser
      responses:
        default:
          description: ''
  '/api/v1/user/{id}':
    delete:
      operationId: delete_app_api_v1_user_deleteuserbyid
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: string
            pattern: \d+
      responses:
        default:
          description: ''
  /api/v1/user/async:
    post:
      operationId: post_app_api_v1_user_saveuserasync
      responses:
        default:
          description: ''
  /api/v1/user/create-user:
    get:
      operationId: get_create_user
      responses:
        default:
          description: ''
    post:
      operationId: post_create_user
      responses:
        default:
          description: ''
  '/api/v1/user/update-user/{id}':
    get:
      operationId: get_update_user
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: ''
    patch:
      operationId: patch_update_user
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: ''
  /api/v2/user:
    get:
      operationId: get_app_api_v2_user_getusers
      responses:
        default:
          description: ''
    post:
      operationId: post_app_api_v2_user_saveuser
      responses:
        default:
          description: ''
  '/api/v2/user/{userId}':
    delete:
      operationId: delete_app_api_v2_user_deleteuser
      parameters:
        -
          name: userId
          in: path
          required: true
          schema:
            type: string
            pattern: \d+
      responses:
        default:
          description: ''
    patch:
      operationId: patch_app_api_v2_user_updateuser
      parameters:
        -
          name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: ''
  /api/v3/user:
    get:
      operationId: get_app_api_v3_user_getusers
      responses:
        default:
          description: ''
    post:
      operationId: post_app_api_v3_user_saveuser
      responses:
        default:
          description: ''
    delete:
      operationId: delete_app_api_v3_user_deleteuser
      responses:
        default:
          description: ''
    patch:
      operationId: patch_app_api_v3_user_updateuser
      responses:
        default:
          description: ''
components:
  schemas:
    CreateUserDTO:
      required:
        - login
        - password
        - roles
        - age
        - is_active
      properties:
        login:
          type: string
          maxLength: 32
        password:
          type: string
          maxLength: 32
        age:
          type: integer
        is_active:
          type: boolean
      type: object

